### ISSUE TITLE
Register this package

### ISSUE THREAD

**Issue by theabhirath** [FluxML/OneHotArrays.jl#12]
Could we register this package? I see there was an abandoned attempt to do that. I would like to use this for some stuff I've been trying on the side 😅

**Comment by ToucheSir** [comment]
The problem with the community being distributed across multiple timezones and only communicating asynchronously is that it's hard to get a bunch of people into one place when a consensus decision (like the ones which needed to be made for registration) is required. Perhaps this thread can be that place.

**Comment by darsnack** [comment]
I recall @cossio mentioning on Slack that it would be fine to just register this as is (I don't think the name shadowing is a big concern here).

**Comment by MilkshakeForReal** [comment]
Time to close this?
