### ISSUE TITLE
Missing `v0.1.0` docs + add docs URL in About section

### ISSUE THREAD

**Issue by Saransh-cpp** [FluxML/OneHotArrays.jl#19]
The docs for `v0.1.0` (https://fluxml.ai/OneHotArrays.jl/v0.1.0/) currently lead to a `404` page. The docs are also missing from the `gh-pages` branch - https://github.com/FluxML/OneHotArrays.jl/tree/gh-pages. The docs should've been generated automatically (I don't know why they weren't in the first place), but they can be generated manually by someone who has push access to `main` -

```
git tag -a v0.1.0+docs -m "Build and deploy docs for v0.1.0"
git push --tags
```

The new `v0.1.0+docs` tag will automatically trigger the `Documenter` workflow to generate and deploy `v0.1.0` docs.

Additionally, the docs URL should be added to project's about section -

![image](https://user-images.githubusercontent.com/74055102/187252553-ed81f0fb-d62d-4858-9de1-26a556eee0d1.png)

**Comment by darsnack** [comment]
> they can be generated manually by someone who has push access to main -
> ```
> git tag -a v0.1.0+docs -m "Build and deploy docs for v0.1.0"
> git push --tags
> ```
> The new v0.1.0+docs tag will automatically trigger the Documenter workflow to generate and deploy v0.1.0 docs.

This is done on the 0.1.0 commit right?
